language: node_js
sudo: required
node_js:
  - 10.0.0
cache:
  directories:
    - node_modules
before_install:
  - export TZ='Asia/Shanghai'  # 设置时区
script:
  - sh $TRAVIS_BUILD/deploy.sh
branch: v1.0.0